# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

# 플랫폼별 Fastfile import
import "ios/Fastfile"
import "android/Fastfile"

# 기본 플랫폼 설정 (필요에 따라 변경)
default_platform(:ios)